---
name: Build - Ubuntu

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - "src/**"
  merge_group:
  push:
    paths:
      - "src/**"
    branches:
      - main

env:
  CMAKE_BUILD_PARALLEL_LEVEL: 2
  MAKEFLAGS: "-j 2"

jobs:
  cancel-runs:
    if: github.event_name == 'pull_request' && github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  job:
    if: ${{ github.event_name == 'push' || !github.event.pull_request.draft }}
    name: ${{ matrix.os }}-${{ matrix.buildtype }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
        buildtype: [linux-release, linux-debug]
        include:
          - os: ubuntu-22.04
            triplet: x64-linux

    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Switch to gcc-11
        if: matrix.os == 'ubuntu-20.04'
        run: |
          sudo apt install gcc-11 g++-11
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 100 --slave /usr/bin/g++ g++ /usr/bin/g++-11 --slave /usr/bin/gcov gcov /usr/bin/gcov-11
          sudo update-alternatives --set gcc /usr/bin/gcc-11

      - name: CCache
        uses: hendrikmuhs/ccache-action@main
        with:
          max-size: "1G"
          key: ccache-${{ matrix.os }}-${{ matrix.buildtype }}
          restore-keys: |
            ccache-${{ matrix.os }}

      - name: Run Build and Tests
        run: |
          cd ${{ github.workspace }}/tests
          chmod +x build_and_run.sh
          ./build_and_run.sh

      - name: Create and Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: canary-${{ matrix.os }}-${{ matrix.buildtype }}-${{ github.sha }}
          path: |
            ${{ github.workspace }}/build/bin/

#      - name: Run Integration Tests
#        run: |
#          cd ${{ github.workspace }}/build/${{ matrix.buildtype }}/tests/integration
#          ctest --verbose
